export const ADD_TAG_TO_NOTE = 'ADD_TAG_TO_NOTE';
export const REMOVE_TAG_FROM_NOTE = 'REMOVE_TAG_FROM_NOTE';
export const ADD_TAG_TO_FILTER = 'ADD_TAG_TO_FILTER';
export const REMOVE_TAG_FROM_FILTER = 'REMOVE_TAG_FROM_FILTER';
